#!/usr/bin/bash
re='\033[0m'
bw='\033[47m'
by='\033[103m'
y='\033[1;93m'
b='\033[1;90m'
echo -e "${bw}             ${y}_             ${re}"
echo -e "${bw}            ${y}/ \\            ${re}"
echo -e "${bw}           ${y}/   \\           ${re}"
echo -e "${bw}          ${y}/     \\          ${re}"
echo -e "${bw}   ${b}|     ${y}/ ${b}_____ ${y}\\     ${b}|   ${re}"
echo -e "${bw}   ${b}|    ${y}/ ${b}/  ╷  \\ ${y}\\    ${b}|   ${re}"
echo -e "${bw}   ${b}|__ ${y}/  ${b}\\_____/  ${y}\\ ${b}__|   ${re}"
echo -e "${bw}      ${y}/             ${y}\\      ${re}"
echo -e "${bw}     ${y}/      ${b}>-<      ${y}\\     ${re}"
echo -e "${bw}    ${y}/                 \\    ${re}"
echo -e "${bw}   ${y}/                   \\   ${re}"
echo -e "${bw}  ${y}/_____________________\\  ${re}"
echo -e "${bw}          ${b}|     |          ${re}"
echo -e "${bw}          ${b}|     |          ${re}"
echo -e "${bw}          ${b}|     |          ${re}"
echo -e "${bw}         ${b}_|    _|          ${re}"
