#!/usr/bin/bash
find -type f -name "#*#" -delete -o -name "*~" -delete -o -name "a.out" -delete -o -name "*.gcno" -delete -o -name "*.gcda" -delete -o -name ".*.swp" -delete -o -name ".#*" -delete
make -s clean 
