#!/usr/bin/env python3

import pyautogui
import time

pyautogui.write("make run", interval=0.05)
pyautogui.hotkey("ctrl", "shift", "t")
pyautogui.write("cd src", interval=0.05)
pyautogui.press("enter")
pyautogui.hotkey("ctrl", "shift", "t")
pyautogui.hotkey("ctrl", "shift", "t")
pyautogui.write("cd ")
pyautogui.hotkey("shift", ".")
pyautogui.hotkey("shift", ".")
pyautogui.write(" ; find8include", interval=0.05)
pyautogui.press("enter")
pyautogui.hotkey("ctrl", "shift", "t")
pyautogui.write("CSAR -a -l", interval=0.05)
pyautogui.press("enter")
pyautogui.hotkey("ctrl", "right")
