#!/usr/bin/env python3

import pyautogui
import time

pyautogui.write("ls", interval=0.01)
pyautogui.press("enter")
#
pyautogui.hotkey("ctrl", "shift", "t")
time.sleep(0.1)
pyautogui.write("cd src ; ls", interval=0.01)
pyautogui.press("enter")
#
pyautogui.hotkey("ctrl", "shift", "t")
time.sleep(0.1)
pyautogui.write("ls", interval=0.01)
pyautogui.press("enter")
#
pyautogui.hotkey("ctrl", "shift", "t")
time.sleep(0.1)
pyautogui.write("ls", interval=0.01)
pyautogui.press("enter")
#
pyautogui.hotkey("ctrl", "shift", "t")
time.sleep(0.1)
pyautogui.write("cd ")
pyautogui.hotkey("shift", ".")
pyautogui.hotkey("shift", ".")
pyautogui.write(" ; clear ; find8include", interval=0.01)
pyautogui.press("enter")
#
pyautogui.hotkey("ctrl", "shift", "t")
time.sleep(0.1)
pyautogui.write("emacs Makefile", interval=0.01)
pyautogui.press("enter")
#
pyautogui.hotkey("ctrl", "shift", "t")
time.sleep(0.1)
pyautogui.write("CSAR -alvr ", interval=0.01)
pyautogui.hotkey("shift", "1")
pyautogui.press("enter")
#
pyautogui.hotkey("ctrl", "right")
time.sleep(0.1)
pyautogui.write("make run", interval=0.01)
