#!/usr/bin/bash

UWhite='\033[4;37m'
Yellow='\033[1;33m'
Red='\033[1;31m'
On_Black='\033[40m'
Base='\033[0;37m'

echo -e "               LE JEU DE LE GTR"
echo -e " - NE PAS REGARDER LE GTR${On_Black}"
echo -e "  \______________/"
echo -e " __/__|______|__\__"
echo -e "/⭕⭕__________⭕⭕\\"
echo -e "|__/__G-PERDUT__\\__|"
echo -e "${On_Black}\\©©${Base}${On_Black}__|_|_|_|_|__©©${Base}${On_Black}}/"

