#!/usr/bin/env lua

array = {"lua", "programming"}
for i=1,2 do
    print(array[i])
end


















































--[[io.write("hello world\n")

print("argument list:")
for i=0, #arg do
    print(arg[i])
end
if #arg == 1 then
   print("there is 1 argument.")
else
   print(string.format("there are %i arguments.", #arg)) 
end
print("for some reason the exec path is not counted")
print("lenght the {\"test1\",\"test2\"} table:")
a = {"test1","test2"}
print(#a)]]--