#!/usr/bin/bash
#!/usr/bin/bash

echo -e "__  _                            IoooooooI  IooooooooI                
\\ \`/ |                           IoooooooI  IoooooooI
 \\__\`!                           IoooooooI  IoooooooI
 / ,' \`-.__________________      IoooooooI  IoooooooI
'-'\\_____                LI\`-.   IoooooooI  IoooooooI
   <____()-=O=O=O=O=O=[]====--)  IoooooooI  IoooooooI
     \`.___ ,-----,_______...-'   IoooooooI  IoooooooI
          /    .'                IoooooooI  IoooooooI
         /   .'                  IoooooooI  IoooooooI
        /  .'                    IoooooooI  IoooooooI
        \`-'                      L___n___⅃  L___n___⅃"
