#!/usr/bin/env python3

import random
import os

quotes = open(os.environ['HOME'] + "/my_scripts/assets/splashes.txt", "r").read().splitlines(True)
print(quotes[random.randint(0, len(quotes) - 1)],end='')
