#!/usr/bin/env python3

import sys
import math
import random

decos = ["o","O","*",".","+","0","'"]
deco_colors = ["\033[1;91m","\033[1;93m","\033[1;94m","\033[1;97m","\033[1;95m","\033[1;96m"]

def leaves (char):
    if (random.randint(0, 9) > 3):
        print("\033[1;92m", end="")
        print(char, end="")
    else:
        print(deco_colors[random.randint(0, 5)], end="")
        print(decos[random.randint(0, 6)], end="")

#invalid input / error handling
if (len(sys.argv) != 2):
    print("invalid arguments, the program only accept one argument.")
    sys.exit(84)
try:
    size = int(sys.argv[1])
except:
    print("invalid argument, size must be an interger.")
    sys.exit(84)
if (size <= 4):
    print("invalid argument,size must be 5 or superior.")
    sys.exit(84)

#printing the tree
print("", end="")
for i in range(size):
    for j in range(size - i - 1):
        print(" ", end="")
    for j in range(i):
        leaves("/")
    if (i == 0):
        print('\033[1;93m' + "X", end="")
    else:
        leaves("|")
    for j in range(i):
        leaves("\\")
    print("")

for i in range(math.ceil(math.sqrt(size))):
    for j in range(size - 2):
        print(" ", end="")
    for j in range(3):
        print('\033[1;33m' + "|", end="")     
    print("")
        
